# Generated by Django 4.2 on 2025-05-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VPNUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Unique VPN username (can include any characters)",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        help_text="Date/time when this user’s VPN credentials expire"
                    ),
                ),
                (
                    "openvpn_password",
                    models.CharField(
                        help_text="Password for OpenVPN connections (separate from Django login)",
                        max_length=128,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the VPN account is active or revoked",
                    ),
                ),
            ],
        ),
    ]
