# Generated by Django 4.2 on 2025-05-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vpnuser",
            name="expiry_date",
            field=models.DateField(
                help_text="Date/time when this user’s VPN credentials expire"
            ),
        ),
    ]
