# Generated by Django 4.2 on 2025-05-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn_manager", "0002_alter_vpnuser_expiry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="vpnuser",
            name="max_connections",
            field=models.PositiveIntegerField(
                default=1, help_text="Maximum simultaneous connections for this user"
            ),
        ),
        migrations.AlterField(
            model_name="vpnuser",
            name="expiry_date",
            field=models.DateField(
                help_text="Date when this user’s VPN credentials expire"
            ),
        ),
    ]
