# Generated by Django 4.2 on 2025-05-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn_manager", "0003_vpnuser_max_connections_alter_vpnuser_expiry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="vpnuser",
            name="has_access_server_user",
            field=models.BooleanField(default=False),
        ),
    ]
