# Generated by Django 4.2 on 2025-05-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn_manager", "0004_vpnuser_has_access_server_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vpnuser",
            name="has_access_server_user",
            field=models.BooleanField(default=True),
        ),
    ]
